export type {
  ResumeData,
  PersonalInfo,
  SectionType,
  SectionBase,
  SummarySection,
  WorkExperienceSection,
  WorkEntry,
  EducationSection,
  EducationEntry,
  SkillsSection,
  SkillCategory,
  ProjectsSection,
  ProjectEntry,
  CertificationsSection,
  CertificationEntry,
  CustomSection,
  Section,
} from '@shared/types/resume'
